(define (problem stack_4_blocks)
    (:domain blocks)
    (:requirements :strips)
  	(:objects red green blue brown)
    (:init
        (hand-empty)
        (on-ground red)
        (on-ground green)
        (on-ground blue)
        (on-ground brown)
        (on-top red)
        (on-top green)
        (on-top blue)
        (on-top brown)
        (distinct red green)
        (distinct green red)
        (distinct red blue)
        (distinct blue red)
        (distinct green blue)
        (distinct blue green)
        (distinct red brown)
        (distinct brown red)
        (distinct green brown)
        (distinct brown green)
        (distinct blue brown)
        (distinct brown blue)
    )
    (:goal (and
        (hand-empty)
        (on-ground red)
        (on green red)
        (on blue green)
        (on brown blue)
        (on-top brown)
      )
    )
)