(define (problem stack_4_blocks)
    (:domain blocks)
    (:requirements :strips :typing)
  	(:objects
  	    red green blue brown - block
  	    ground - surface
    )
    (:init
        (hand-empty)
        (on red ground)
        (on green ground)
        (on blue ground)
        (on brown ground)
        (on-top red)
        (on-top green)
        (on-top blue)
        (on-top brown)
        (distinct red green)
        (distinct green red)
        (distinct red blue)
        (distinct blue red)
        (distinct green blue)
        (distinct blue green)
        (distinct red brown)
        (distinct brown red)
        (distinct green brown)
        (distinct brown green)
        (distinct blue brown)
        (distinct brown blue)
    )
    (:goal (and
        (hand-empty)
        (on red ground)
        (on green red)
        (on blue green)
        (on brown blue)
        (on-top brown)
      )
    )
)